import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Kanit, Prompt } from 'next/font/google'

import NextAuthSessionProvider from "./providers/SessionProvider";

const kanit = Kanit({
  subsets: ['latin', 'thai'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
})

// หรือ Prompt
const prompt = Prompt({
  subsets: ['latin', 'thai'],
  weight: ['300', '400', '500', '600', '700'],
  display: 'swap',
})


// const geistSans = Geist({
//   variable: "--font-kanit",
//   subsets: ['thai', 'latin'],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BotAssistant",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="th" className={kanit.className}>
      <body
       
      >
        <NextAuthSessionProvider>
          <main className="min-h-screen flex flex-col m-auto" style={{ maxWidth: '600px'}}>
            <div className="flex-1 md:p-8">{children}</div>
          </main>
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
